server:
  port: 8090

spring:
  application:
    name: ribbon-consumer-example
  cloud:
    loadbalancer:
      ribbon:
        # 默认开启负载均衡策略
        enabled: true


# eureka 配置
eureka:
  instance:
    # 该属性用在 Client 端，设置为 true，则表示使用IP向注册中心注册；否则使用主机名注册
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

# 服务消费者整合 Ribbon 之后，会为每个服务提供者（在称为 Client）实例化并初始化一个负载均衡器（DynamicServerListLoadBalancer）
ribbon:
  eager-load:
    # 开启 Ribbon 饥饿加载模式（加载 Ribbon 配置），默认 false，即懒加载。
    enabled: true
    # 指定需要饥饿加载模式的 Client
    clients: RIBBON-PROVIDER1-EXAMPLE, RIBBON-PROVIDER2-EXAMPLE, RIBBON-PROVIDER3-EXAMPLE
