server:
#  port: 8082
  port: 8083

spring:
  application:
    name: ribbon-provider2-example

# eureka 配置
eureka:
  instance:
    # 该属性用在 Client 端，设置为 true，则表示使用IP向注册中心注册；否则使用主机名注册
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


